#ifndef PIXELGAME_GRAPHICS_CONSTANS_H
#define PIXELGAME_GRAPHICS_CONSTANS_H

const static double MAIN_Z = 100, BACKGROUND_OBJECTS_Z = 150;
const static double PARALLAX_COEFFICIENT_X = 0.5, PARALLAX_COEFFICIENT_Y = 0.1;

#endif //PIXELGAME_GRAPHICS_CONSTANS_H
