#ifndef PIXELGAME_ENVIRONMENT_CONSTANS_H
#define PIXELGAME_ENVIRONMENT_CONSTANS_H

static const int CHUNK_SIZE = 128;
static const int WORLD_WIDTH_IN_CHUNKS = 128, WORLD_HEIGHT_IN_CHUNKS = 32;
static const int WORLD_WIDTH_IN_UNITS = WORLD_WIDTH_IN_CHUNKS * CHUNK_SIZE, WORLD_HEIGHT_IN_UNITS = WORLD_HEIGHT_IN_CHUNKS * CHUNK_SIZE;
#endif //PIXELGAME_ENVIRONMENT_CONSTANS_H
